networks:
  forte9_lan:
    driver: bridge

volumes:
  forte9_pg_data:

services:
  forte9-backend:
    container_name: forte9-backend
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: DEVELOPMENT
      CORS_ORIGINS: http://localhost:3000
      PG_DSN: postgresql://forte9_dev:forte9_dev@postgres:5432/forte9_dev
    build: ./backend
    networks:
      - forte9_lan
    ports:
      - 8400:8400
    restart: unless-stopped
    volumes:
      - ./backend/static:/app/static

  forte9-frontend:
    container_name: forte9-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8400
      NEXT_PUBLIC_HCAPTCHA_SITE_KEY: 10000000-ffff-ffff-ffff-000000000001
    build: ./frontend
    ports:
      - 3000:3000
    restart: unless-stopped

  postgres:
    environment:
      POSTGRES_DB: forte9_dev
      POSTGRES_PASSWORD: forte9_dev
      POSTGRES_USER: forte9_dev
    image: postgres
    networks:
      - forte9_lan
    restart: always
    volumes:
      - forte9_pg_data:/var/lib/postgresql/data
